name: Build Chocofi Knob Studio

on:
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["rpi_pico"]'
      shield: '["chocofi_knob"]'
      alphas: '["QWERTY"]'
      branches: '["zmkfirmware/zmk/v0.3"]'
